version: '2'

services:
  reviewservice:
    image: metheora/review-service
    build: .
    ports:
      - "5060:5060"
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db