version: '2'

services:
  reviewservice:
    image: user/reviewservice${TAG}
    build: .
    ports:
      - "5060:5060"
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"